### ISSUE TITLE
addon blocks moving the character frame

### ISSUE THREAD

**Issue by Numynum** [Sluimerstand/EquipRecommendedGear#10]
this addon seems to cause issues when moving the character frame, e.g. with blizzmove
see https://github.com/Kiatra/BlizzMove/issues/124

I'm pretty sure removing this `SetPoint('CENTER')` fixes it (https://github.com/Sluimerstand/EquipRecommendedGear/blob/abfa8c4a39fe5c88d12f365d113fc5ca794402ee/Core.lua#L106)
additionally, there's no need for your button to inherit SecureActionButtonTemplate, especially since you replace the OnClick script handler
removing that, would be a good idea 🙂

**Comment by Sluimerstand** [comment]
You are entirely right, not sure why I had a double `SetPoint()` in there to begin with. Fixed with 732f50c.

As for your advice on the `SecureActionButtonTemplate`, I always thought buttons had to have at least 1 template, and I'd copied this from another project's Cooking Fire button without thinking about it too much. This is now rectified with ab17823, thank you for the advice!
